# Try/Except

# Primeiramente tentará executar o try, caso ocorra alguma exceção ele executará o except.
# Algo tão simples é considerado uma má prática.
try:
    # print(ola)
    pass
    
except:
    print('Erro')
